### ISSUE TITLE
console.cloud.google.com下拉取不到

### ISSUE THREAD

**Issue by novvoo** [mritd/gcr#1]
像这类的grcxio拉取不到
[https://console.cloud.google.com](https://console.cloud.google.com/gcr/images/spinnaker-marketplace/GLOBAL/igor@sha256:aca9fc07d0b6ca8cecf14d5aa0bfd286d9d5611c9d23855e2eb202331660747a/details?tab=info)

```
docker pull gcr.io/spinnaker-marketplace/igor:0.9.0-20180221133510
```

**Comment by mritd** [comment]
可能是部分镜像没有成功被推送，稍后我手动同步一下，争取完善一下增量同步机制

**Comment by novvoo** [comment]
你有用微信吗 给你发邮箱了，你这个项目还不错。
刚在折腾spinnaker这个CI工具，helm很多都是从console.cloud.google.com拉取的，很麻烦

**Comment by mritd** [comment]
刚刚测试了一下，镜像有....由于当前只有一个用户，所以中间的 namesapce 直接丢弃了

```sh
docker pull gcrxio/igor:0.9.0-20180221133510
```
