### ISSUE TITLE
Azure的仓库是不是最近一段时间都不可用了

### ISSUE THREAD

**Issue by xfangfang** [mritd/gcr#2]
感谢您的付出，一直在使用 gcr.azk8s.cn 下的 gcr.io镜像，不过最近一段时间没有办法使用了，访问gcr.azk8s.cn出现403，请问是不是gcr.azk8s.cn出了什么问题呢？

**Comment by mritd** [comment]
@xfangfang azure 已经禁止外部 IP 拉取镜像 
![image](https://user-images.githubusercontent.com/13043245/79684850-0ed05c80-8267-11ea-95fe-b88b4533ed8b.png)

本项目正在重启，代码在重新优化

refs mritd/imgsync#4

**Comment by mritd** [comment]
目前 imgsync 还未编写完成，目标同步仓库已经在 README 中列出，如果需要增加其他仓库可开启 issue。
